spring:
  application:
    name: planfAi
  datasource:
    url: jdbc:mysql://localhost:3306/planfai?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: com.whomade.planfAi.profitReport.vo
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
